"""Added picture path column to the pets table.

Revision ID: 094192d2cda2
Revises: f2f9ad4d4348
Create Date: 2019-05-02 14:33:38.598813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094192d2cda2'
down_revision = 'f2f9ad4d4348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('pet_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'pet_pic_path')
    # ### end Alembic commands ###
